[project]
name = "ofxstatement-dutch"
version = "1.8.0"
authors = [{name = "Gert-Jan Paulissen", email = "12508981+gpaulissen@users.noreply.github.com"}]
license = "GPL-3.0-or-later"
description = "OFXStatement plugin for dutch financial institutions like DEGIRO, ICSCards, ING, KNAB and ASN."
keywords = [
    "ofx",
    "banking",
    "statement",
    "beancount",
    "degiro",
    "ing",
    "icscards",
    "knab",
]
classifiers = [
    "Development Status :: 6 - Mature",
    "Programming Language :: Python :: 3",
    "Natural Language :: English",
    "Topic :: Office/Business :: Financial :: Accounting",
    "Topic :: Utilities",
    "Environment :: Console",
    "Operating System :: OS Independent",
]
dependencies = ["ofxstatement>=0.9.1", "pdftotext"]
requires-python = ">=3.9"
readme = "README.md"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/gpaulissen/ofxstatement-dutch"

[project.scripts]
nl-degiro = "ofxstatement_dutch.degiro:Plugin"
nl-icscards = "ofxstatement_dutch.icscards:Plugin"
nl-ing = "ofxstatement_dutch.ing:Plugin"
nl-knab = "ofxstatement_dutch.knab:Plugin"
nl-asn = "ofxstatement_dutch.asn:Plugin"

[project.optional-dependencies]
dev = [
    "pyyaml",
    "pytest",
    "pytest-cache",
    "pytest-cov",
		"ruff",
		"pre-commit"
]

[tool.setuptools]
zip-safe = true
include-package-data = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=src --cov-report term-missing --cov-report html --no-cov-on-fail --doctest-modules"
testpaths = [
    "tests",
]

[tool.mypy]
strict = true
disallow_subclassing_any = false

[[tool.mypy.overrides]]
module = [ 'ofxstatement', 'bs4' ]
ignore_missing_imports = true

[tool.ruff]
# Exclude common directories that are typically not part of the source code or are generated by tools.
exclude = [
    ".bzr",
    ".devbox",
    ".direnv",
    ".eggs",
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".git",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "venv"
]

# Set the maximum line length to 200 characters.
line-length = 210

# Define the number of spaces used for indentation, aligning with Black's style.
indent-width = 4

# The minimum Python version to target, e.g., when considering automatic code upgrades,
# like rewriting type annotations
target-version = "py38"

[tool.ruff.lint]
# Enable Pyflakes (F) and a subset of the pycodestyle (E) codes by default.
# Enable the isort rules (I) to replace isort
# pycodestyle warnings (W)
# Activate Security Rules (S) to replace bandit
# flake8-bugbear (B)
# flake8-simplify (SIM)

select = ["E", "F", "I"]
extend-select = ["E4", "E7", "E9", "W", "S", "B", "SIM"]
ignore = ["B009", "B010", "S603", "SIM115"] # List any rules to be ignored

# Allow auto-fixing of all enabled rules when using the `--fix` option.
fixable = ["ALL"]
unfixable = [] # Specify rules that cannot be auto-fixed, if any.

# Define a regex pattern for allowed unused variables (typically underscore-prefixed).
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Enforce double quotes for strings, following Black's style.
quote-style = "double"

# Use spaces for indentation, in line with Black's formatting style.
indent-style = "space"

# Keep magic trailing commas, a feature of Black's formatting.
skip-magic-trailing-comma = false

# Automatically detect and use the appropriate line ending style.
line-ending = "auto"
